# Generated by Django 4.1.6 on 2023-02-16 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home_page',
            name='slider_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='media/homepage/'),
        ),
    ]
