# Generated by Django 4.1.6 on 2023-02-16 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_alter_home_page_slider_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='home_page',
            new_name='home_page_slider',
        ),
    ]
