# Generated by Django 4.1.6 on 2023-06-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_rename_home_page_home_page_slider'),
    ]

    operations = [
        migrations.CreateModel(
            name='home_page_categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories_img', models.FileField(default=None, max_length=250, null=True, upload_to='homepage_categories/')),
            ],
        ),
        migrations.AlterField(
            model_name='home_page_slider',
            name='slider_image',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='homepage/'),
        ),
    ]
