# Generated by Django 4.1.6 on 2023-06-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_home_page_categories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='home_page_categories',
            name='category_name',
            field=models.CharField(default='test', max_length=20),
        ),
        migrations.AddField(
            model_name='home_page_slider',
            name='sliderimg_name',
            field=models.CharField(default='test', max_length=20),
        ),
    ]
