# Generated by Django 4.1.6 on 2023-06-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='originalprice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
